version: "3.7"

networks:
  gigo:
    external: false

volumes:
  ziti-fs:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ./data/ziti

services:
  gigo-dev-tidb:
    image: gigodev/tidb-playground:latest
    restart: always
    networks:
      - gigo
#    ports:
#      - "4000:4000"
#      - "10080:10080"
#      - "2379:2379"

  gigo-dev-git:
    image: gitea/gitea:latest
    command: "/bin/bash /custom-entrypoint.sh"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__install__DISABLE_REGISTRATION=true
      - GITEA__install__DEFAULT_ALLOW_CREATE_ORGANIZATION=false
    volumes:
      - ./data/gitea/app.ini:/data/gitea/conf/app.ini
      - ./data/gitea/entrypoint.sh:/custom-entrypoint.sh
    restart: always
    networks:
      - gigo
    # ports:
    #   - "4214:3000"

  gigo-dev-nats:
    image: nats:latest
    command: "-js"
    restart: always
    networks:
      - gigo
#    ports:
#      - "4222:4222"
#      - "8222:8222"
#      - "6222:6222"

  gigo-dev-minio:
    image: quay.io/minio/minio:latest
    entrypoint: /bin/sh
    command: /custom-entrypoint.sh
    restart: always
    environment:
      - MINIO_ROOT_USER=gigo-dev
      - MINIO_ROOT_PASSWORD=gigo-dev
    volumes:
      - ./data/minio/entrypoint.sh:/custom-entrypoint.sh
      - ./data/minio/initData:/tmp/initData
    networks:
      - gigo
    # ports:
    #   - "9101"
    #   - "9000"

  gigo-dev-meili:
    image: getmeili/meilisearch:latest
    command: meilisearch --env=development
    restart: always
    environment:
      - MEILI_MASTER_KEY=gigo-dev
    networks:
      - gigo
#    ports:
#      - "7700:7700"
#      - "7701:7701"

  gigo-dev-redis:
    image: redis/redis-stack:latest
    restart: always
    environment:
      - REDIS_ARGS=--requirepass gigo-dev
    networks:
      - gigo
#    ports:
#      - "6379:6379"

  gigo-dev-etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: always
    networks:
      - gigo
#    ports:
#      - "2379:2379"

  gigo-dev-ziti-controller:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    healthcheck:
      test: curl -m 1 -s -k https://${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}:${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}/edge/client/v1/version
      interval: 1s
      timeout: 3s
      retries: 30
    env_file:
      - ./.env
    ports:
      - ${ZITI_INTERFACE:-0.0.0.0}:${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}:${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}
      - ${ZITI_INTERFACE:-0.0.0.0}:${ZITI_CTRL_ADVERTISED_PORT:-6262}:${ZITI_CTRL_ADVERTISED_PORT:-6262}
    environment:
      - ZITI_CTRL_NAME=${ZITI_CTRL_NAME:-gigo-dev-ziti-controller}
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}
      - ZITI_CTRL_EDGE_IP_OVERRIDE=${ZITI_CTRL_EDGE_IP_OVERRIDE:-127.0.0.1}
      - ZITI_CTRL_ADVERTISED_PORT=${ZITI_CTRL_ADVERTISED_PORT:-6262}
      - ZITI_EDGE_IDENTITY_ENROLLMENT_DURATION=${ZITI_EDGE_IDENTITY_ENROLLMENT_DURATION}
      - ZITI_ROUTER_ENROLLMENT_DURATION=${ZITI_ROUTER_ENROLLMENT_DURATION}
      - ZITI_USER=${ZITI_USER:-admin}
      - ZITI_PWD=${ZITI_PWD}
    networks:
      - gigo
    volumes:
      - ziti-fs:/persistent
    entrypoint:
      - "/var/openziti/scripts/run-controller.sh"

  gigo-dev-ziti-controller-init-container:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    depends_on:
      gigo-dev-ziti-controller:
        condition: service_healthy
    environment:
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}
    env_file:
      - ./.env
    networks:
      - gigo
    volumes:
      - ziti-fs:/persistent
    entrypoint:
      - "/var/openziti/scripts/run-with-ziti-cli.sh"
    command:
      - "/var/openziti/scripts/access-control.sh"

  gigo-dev-ziti-edge-router:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    env_file:
      - ./.env
    depends_on:
      gigo-dev-ziti-controller:
        condition: service_healthy
    ports:
      - ${ZITI_INTERFACE:-0.0.0.0}:${ZITI_ROUTER_PORT:-3022}:${ZITI_ROUTER_PORT:-3022}
      - ${ZITI_INTERFACE:-0.0.0.0}:${ZITI_ROUTER_LISTENER_BIND_PORT:-10080}:${ZITI_ROUTER_LISTENER_BIND_PORT:-10080}
    environment:
      - ZITI_CTRL_ADVERTISED_ADDRESS=${ZITI_CTRL_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}
      - ZITI_CTRL_ADVERTISED_PORT=${ZITI_CTRL_ADVERTISED_PORT:-6262}
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}
      - ZITI_ROUTER_NAME=${ZITI_ROUTER_NAME:-gigo-dev-ziti-edge-router}
      - ZITI_ROUTER_ADVERTISED_ADDRESS=${ZITI_ROUTER_ADVERTISED_ADDRESS:-gigo-dev-ziti-edge-router}
      - ZITI_ROUTER_PORT=${ZITI_ROUTER_PORT:-3022}
      - ZITI_ROUTER_LISTENER_BIND_PORT=${ZITI_ROUTER_LISTENER_BIND_PORT:-10080}
      - ZITI_ROUTER_ROLES=public
    networks:
      - gigo
    volumes:
      - ziti-fs:/persistent
    entrypoint: /bin/bash
    command: "/var/openziti/scripts/run-router.sh edge"

  gigo-dev-ziti-console:
    image: openziti/zac
    working_dir: /usr/src/app
    environment:
      - ZAC_SERVER_CERT_CHAIN=/persistent/pki/${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}-intermediate/certs/${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}-server.cert
      - ZAC_SERVER_KEY=/persistent/pki/${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}-intermediate/keys/${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}-server.key
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-gigo-dev-ziti-controller}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}
      - ZITI_CTRL_NAME=${ZITI_CTRL_NAME:-gigo-dev-ziti-controller}
      - PORTTLS=8443
    depends_on:
      gigo-dev-ziti-controller:
        condition: service_healthy
    ports:
      - ${ZITI_INTERFACE:-0.0.0.0}:8443:8443
    volumes:
      - ziti-fs:/persistent
    networks:
      - gigo

  gigo-dev-runner:
    image: gigodev/gimg:go-ubuntu
    restart: always
    volumes:
      - ./runner.sh:/runner.sh
    env_file:
      - .env
    networks:
      - gigo
    depends_on:
      - gigo-dev-git
      - gigo-dev-nats
      - gigo-dev-minio
      - gigo-dev-meili
      - gigo-dev-redis
      - gigo-dev-etcd
      - gigo-dev-ziti-controller
    command: /bin/bash /runner.sh
    